apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: calico-host-endpoint-controller-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["crd.projectcalico.org"]
  resources: ["hostendpoints"]
  verbs:
   - create
   - get
   - list
   - update
   - delete
   # To use kubectl apply on resources that already exist
   - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: calico-host-endpoint-controller-role-binding
subjects:
- kind: ServiceAccount
  name: calico-host-endpoint-controller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: calico-host-endpoint-controller-role
  apiGroup: rbac.authorization.k8s.io
